name: flutter_challenge
description: A Flutter project to the challenge.
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/emails.json
  
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
